// ════════════════════════════════════════════
//  UTILS — Shared helper functions
// ════════════════════════════════════════════

// ── HTML escaping ────────────────────────────

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}


function renderRichText(text) {
  if (!text) return '';
  let s = escHtml(text);
  s = s.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  s = s.replace(/\n/g, '<br>');
  return sanitizeHtml(s);
}

// ── HTML sanitization ────────────────────────
// Allowlist-based sanitizer for HTML generated by renderRichText().
// Strips any tag not in the allowlist and removes dangerous attributes
// (event handlers, javascript: hrefs) from allowed tags.

function sanitizeHtml(html) {
  if (!html) return '';
  const ALLOWED_TAGS = new Set(['strong', 'em', 'br', 'a', 'span']);
  // Allowlist-based: only keep the tag itself (and, for <a>, a validated href).
  // This is safer than stripping individual dangerous attributes because it
  // cannot be bypassed by unusual attribute formatting.
  let s = html.replace(/<([a-z][a-z0-9]*)((?:\s[^>]*)?)\s*\/?>/gi, (match, tag, attrs) => {
    const lowerTag = tag.toLowerCase();
    if (!ALLOWED_TAGS.has(lowerTag)) return '';
    // For <a> tags extract only a safe href attribute; drop everything else
    if (lowerTag === 'a') {
      const hrefMatch = (attrs || '').match(/\s+href\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/i);
      if (hrefMatch) {
        const raw = hrefMatch[1] !== undefined ? hrefMatch[1]
                  : hrefMatch[2] !== undefined ? hrefMatch[2]
                  : hrefMatch[3] || '';
        // Normalize: strip whitespace/control chars that can bypass protocol checks
        const href = raw.replace(/[\s\u0000-\u001f]/g, '');
        if (/^(https?:|tel:|mailto:)/i.test(href)) {
          return `<a href="${href}">`;
        }
      }
      return '<a>';
    }
    // All other allowed tags: keep the tag name only, drop all attributes
    return `<${lowerTag}>`;
  });
  // Remove closing tags for disallowed elements
  s = s.replace(/<\/([a-z][a-z0-9]*)\s*>/gi, (match, tag) => {
    return ALLOWED_TAGS.has(tag.toLowerCase()) ? `</${tag.toLowerCase()}>` : '';
  });
  return s;
}

// ── PIN / credentials hashing ────────────────
// Output format: base64(salt) + ':' + base64(derivedKey)
// Legacy SHA-256 hashes (64-char hex, no colon) are still accepted by verifyPin().

const PBKDF2_ITERATIONS = 600000;
const PBKDF2_SALT_BYTES = 16;
const PBKDF2_KEY_BYTES  = 32;

async function hashPin(pin, existingSalt) {
  const enc  = new TextEncoder();
  const salt = existingSalt
    ? Uint8Array.from(atob(existingSalt), c => c.charCodeAt(0))
    : crypto.getRandomValues(new Uint8Array(PBKDF2_SALT_BYTES));

  const keyMaterial = await crypto.subtle.importKey(
    'raw', enc.encode(pin), 'PBKDF2', false, ['deriveBits']
  );
  const derived = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' },
    keyMaterial,
    PBKDF2_KEY_BYTES * 8
  );
  const saltB64 = btoa(String.fromCharCode(...salt));
  const hashB64 = btoa(String.fromCharCode(...new Uint8Array(derived)));
  return saltB64 + ':' + hashB64;
}

// Constant-time comparison to prevent timing attacks.
// Supports legacy plain SHA-256 hashes (64-char hex, no colon) for backward compatibility.
// On first successful login with an old hash, the caller should re-hash and store PBKDF2 format.
async function verifyPin(pin, storedHash) {
  if (!storedHash || !pin) return false;

  // Legacy: plain SHA-256 (64-char hex, no colon)
  if (/^[a-f0-9]{64}$/.test(storedHash)) {
    const buf    = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(pin));
    const legacy = Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
    return legacy === storedHash;
  }

  // PBKDF2 format: base64salt:base64hash
  const colonIdx = storedHash.indexOf(':');
  if (colonIdx === -1) return false;
  const salt    = storedHash.substring(0, colonIdx);
  const newHash = await hashPin(pin, salt);
  if (newHash.length !== storedHash.length) return false;
  let diff = 0;
  for (let i = 0; i < newHash.length; i++) {
    diff |= newHash.charCodeAt(i) ^ storedHash.charCodeAt(i);
  }
  return diff === 0;
}

// ── UI feedback helpers ───────────────────────
// Single implementation replacing duplicate showErr/showOk definitions.

function showMsg(el, text, type) {
  if (!el) { alert((type === 'error' ? '❌ ' : '✅ ') + text); return; }
  el.style.color = type === 'error' ? 'var(--accent)' : 'var(--teal)';
  el.textContent = (type === 'error' ? '❌ ' : '✅ ') + text;
}

function showErr(el, text) { showMsg(el, text, 'error'); }
function showOk(el, text)  { showMsg(el, text, 'ok'); }
